Edited first paragraph as a test
htm-community/building-htm-systems pull request #3
Opened 2019-01-29 21:51 UTC by subutai

2019-01-29 21:51 UTC, subutai commented
@rhyolight Here's a test PR

2019-01-30 01:04 UTC, rhyolight approved these changes

2019-01-30 01:05 UTC, rhyolight requested changes
Can you make the change to the YAML? I have it set up so the JSON can be ignored. I'll clean up it up a bit after.

2019-01-30 04:55 UTC, subutai commented
@rhyolight Done.

2019-02-04 18:23 UTC, closed without merging